#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="bank")]
public partial class DataClassesDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  partial void InserttblAcount(tblAcount instance);
  partial void UpdatetblAcount(tblAcount instance);
  partial void DeletetblAcount(tblAcount instance);
  #endregion
	
	public DataClassesDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["bankConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<tblAcount> tblAcounts
	{
		get
		{
			return this.GetTable<tblAcount>();
		}
	}
	
	public System.Data.Linq.Table<tblmoney> tblmoneys
	{
		get
		{
			return this.GetTable<tblmoney>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblAcount")]
public partial class tblAcount : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private string @__code;
	
	private string @__pass;
	
	private string @__name;
	
	private System.Nullable<decimal> @__current;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void On_codeChanging(string value);
    partial void On_codeChanged();
    partial void On_passChanging(string value);
    partial void On_passChanged();
    partial void On_nameChanging(string value);
    partial void On_nameChanged();
    partial void On_currentChanging(System.Nullable<decimal> value);
    partial void On_currentChanged();
    #endregion
	
	public tblAcount()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[_code]", Storage="__code", DbType="VarChar(60) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string _code
	{
		get
		{
			return this.@__code;
		}
		set
		{
			if ((this.@__code != value))
			{
				this.On_codeChanging(value);
				this.SendPropertyChanging();
				this.@__code = value;
				this.SendPropertyChanged("_code");
				this.On_codeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[_pass]", Storage="__pass", DbType="VarChar(60)")]
	public string _pass
	{
		get
		{
			return this.@__pass;
		}
		set
		{
			if ((this.@__pass != value))
			{
				this.On_passChanging(value);
				this.SendPropertyChanging();
				this.@__pass = value;
				this.SendPropertyChanged("_pass");
				this.On_passChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[_name]", Storage="__name", DbType="VarChar(60)")]
	public string _name
	{
		get
		{
			return this.@__name;
		}
		set
		{
			if ((this.@__name != value))
			{
				this.On_nameChanging(value);
				this.SendPropertyChanging();
				this.@__name = value;
				this.SendPropertyChanged("_name");
				this.On_nameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[_current]", Storage="__current", DbType="Money")]
	public System.Nullable<decimal> _current
	{
		get
		{
			return this.@__current;
		}
		set
		{
			if ((this.@__current != value))
			{
				this.On_currentChanging(value);
				this.SendPropertyChanging();
				this.@__current = value;
				this.SendPropertyChanged("_current");
				this.On_currentChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblmoney")]
public partial class tblmoney
{
	
	private string @__user;
	
	private string @__type;
	
	private System.Nullable<decimal> @__withdraw;
	
	private string @__date;
	
	public tblmoney()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[_user]", Storage="__user", DbType="VarChar(60)")]
	public string _user
	{
		get
		{
			return this.@__user;
		}
		set
		{
			if ((this.@__user != value))
			{
				this.@__user = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[_type]", Storage="__type", DbType="VarChar(60)")]
	public string _type
	{
		get
		{
			return this.@__type;
		}
		set
		{
			if ((this.@__type != value))
			{
				this.@__type = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[_withdraw]", Storage="__withdraw", DbType="Money")]
	public System.Nullable<decimal> _withdraw
	{
		get
		{
			return this.@__withdraw;
		}
		set
		{
			if ((this.@__withdraw != value))
			{
				this.@__withdraw = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[_date]", Storage="__date", DbType="VarChar(60)")]
	public string _date
	{
		get
		{
			return this.@__date;
		}
		set
		{
			if ((this.@__date != value))
			{
				this.@__date = value;
			}
		}
	}
}
#pragma warning restore 1591
